
DTC =({
	"0101": "-MAP sensor circuit low voltage",
	"0102": "-MAP sensor circuit high voltage",
	"0201": "-MAP sensor performance problem",
	"0701": "-ECT sensor circuit low voltage",
	"0702": "-ECT sensor circuit high voltage",
	"0801": "-TPS low voltage",
	"0802": "-TPS sensor circuit high voltage",
	"0901": "-IAT sensor circuit low voltage",
	"0902": "-IAT sensor circuit high voltage",
	"1b01": "-VS sensor no signal",
	"0c01": "-primary injector circuit malfunction",
	"0d01": "-No.2 primary injector circuit malfunction",
	"0e01": "-No.3 primary injector circuit malfunction",
	"0f01": "-No.4 primary injector circuit malfunction",
	"1001": "-No.1 secondary injector circuit malfunction",
	"1101": "-No.2 secondary injector circuit malfunction",
	"1201": "-CMP sensor no signal",
	"1301": "-CKP sensor no signal",
	"1501": "-0₂ sensor malfunction",
	"1701": "-0₂ sensor heater malfunction",
	"1902": "-Knock sensor circuit malfunction",
	"1903": "-Knock sensor circuit malfunction",
	"1d01": "-IACV circuit malfunction",
	"2102": "-ECM EEPROM malfunction",
	"2201": "-ECV POT low voltage malfunction",
	"2202": "-ECV POT high voltage malfunction",
	"2301": "-EGCA malfunction",
	"3001": "-No.3 secondary injector circuit malfunction",
	"3101": "-No.4 secondary injector circuit malfunction",
	"3301": "-HESD linear solenoid malfunction",
	"3601": "-Bank angle sensor circuit low voltage",
	"3602": "-Bank angle sensor circuit high voltage",
	"3801": "-Knock sensor IC malfunction",
	"5601": "-Serial communication malfunction"})
 
